# Auto-merge bot configuration for automated PR merging
# This helps streamline the review process for trusted contributors

# Configuration for auto-merge
autoMerge:
  # Enable auto-merge for specific conditions
  enabled: true
  
  # Conditions for auto-merge
  conditions:
    # Only auto-merge if all checks pass
    - "status-success"
    # Only auto-merge if PR is approved
    - "approved"
    # Only auto-merge if no conflicts
    - "no-conflicts"
    # Only auto-merge if up to date with base branch
    - "up-to-date"
  
  # Labels that enable auto-merge
  autoMergeLabels:
    - "auto-merge"
    - "dependencies"
    - "dependabot"
  
  # Labels that disable auto-merge
  disableAutoMergeLabels:
    - "do-not-merge"
    - "needs-review"
    - "breaking-change"
    - "security"
  
  # Comment to add when auto-merging
  autoMergeComment: |
    🤖 Auto-merging this PR because:
    - All checks have passed ✅
    - PR has been approved ✅
    - No conflicts detected ✅
    - Up to date with base branch ✅
    
    Thank you for your contribution! 🚀
  
  # Comment to add when auto-merge is disabled
  disableAutoMergeComment: |
    🚫 Auto-merge is disabled for this PR because:
    - One or more checks are failing ❌
    - PR needs review ❌
    - Conflicts detected ❌
    - Not up to date with base branch ❌
    
    Please address the issues above and we'll review again.

# Configuration for dependency updates
dependencyAutoMerge:
  # Auto-merge dependency updates from Dependabot
  enabled: true
  
  # Only auto-merge minor and patch updates
  allowedUpdateTypes:
    - "minor"
    - "patch"
  
  # Don't auto-merge major version updates
  blockedUpdateTypes:
    - "major"
  
  # Labels that enable dependency auto-merge
  autoMergeLabels:
    - "dependencies"
    - "dependabot"
    - "auto-merge"
  
  # Comment for dependency auto-merge
  dependencyAutoMergeComment: |
    🤖 Auto-merging dependency update because:
    - This is a minor/patch update ✅
    - All checks have passed ✅
    - No breaking changes detected ✅
    
    Dependencies are now up to date! 🔄

# Configuration for security updates
securityAutoMerge:
  # Auto-merge security updates
  enabled: true
  
  # Only auto-merge security updates
  allowedUpdateTypes:
    - "security"
  
  # Labels that enable security auto-merge
  autoMergeLabels:
    - "security"
    - "auto-merge"
  
  # Comment for security auto-merge
  securityAutoMergeComment: |
    🔒 Auto-merging security update because:
    - This is a security fix ✅
    - All checks have passed ✅
    - No breaking changes detected ✅
    
    Security vulnerability has been patched! 🛡️
