# Dependabot configuration for automated dependency updates
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "⬆️(deps)"
      include: "scope"
    reviewers:
      - "omsherikar"
    assignees:
      - "omsherikar"
    labels:
      - "dependencies"
      - "automated"

  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "⬆️(deps)"
      include: "scope"
    reviewers:
      - "omsherikar"
    assignees:
      - "omsherikar"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    open-pull-requests-limit: 10
    ignore:
      # Ignore major version updates that might break compatibility
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies (if you add Docker support later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "⬆️(deps)"
      include: "scope"
    reviewers:
      - "omsherikar"
    assignees:
      - "omsherikar"
    labels:
      - "dependencies"
      - "docker"
      - "automated"