# Welcome bot configuration for new contributors
# This helps onboard new contributors and makes them feel welcome

# Configuration for new issues
newIssueWelcomeComment: |
  👋 Welcome to Refactron! Thanks for opening an issue.
  
  To help us help you better, please make sure you've:
  - [ ] Searched existing issues to avoid duplicates
  - [ ] Provided a clear description of the problem
  - [ ] Included steps to reproduce (if applicable)
  - [ ] Added relevant labels (if you have permission)
  
  **Quick Links:**
  - 📖 [Documentation](https://github.com/Refactron-ai/Refactron_lib/blob/main/README.md)
  - 🐛 [Bug Report Template](https://github.com/Refactron-ai/Refactron_lib/issues/new?template=bug_report.md)
  - ✨ [Feature Request Template](https://github.com/Refactron-ai/Refactron_lib/issues/new?template=feature_request.md)
  - 🤝 [Contributing Guide](https://github.com/Refactron-ai/Refactron_lib/blob/main/CONTRIBUTING.md)
  
  We'll review your issue and get back to you soon! 🚀

# Configuration for new pull requests
newPRWelcomeComment: |
  🎉 Thanks for contributing to Refactron! We appreciate your effort.
  
  Before we review your PR, please make sure you've:
  - [ ] Read our [Contributing Guide](https://github.com/Refactron-ai/Refactron_lib/blob/main/CONTRIBUTING.md)
  - [ ] Added tests for your changes
  - [ ] Updated documentation if needed
  - [ ] Ensured all tests pass
  - [ ] Followed our code style guidelines
  
  **Quick Links:**
  - 📖 [Documentation](https://github.com/Refactron-ai/Refactron_lib/blob/main/README.md)
  - 🧪 [Running Tests](https://github.com/Refactron-ai/Refactron_lib/blob/main/GETTING_STARTED_DEV.md#running-tests)
  - 📝 [Code Style](https://github.com/Refactron-ai/Refactron_lib/blob/main/CONTRIBUTING.md#code-style)
  
  We'll review your PR and provide feedback soon! 🚀

# Configuration for new contributors
newContributorWelcomeComment: |
  🎊 Welcome to the Refactron community! We're excited to have you here.
  
  **Getting Started:**
  - 📖 [Read the README](https://github.com/Refactron-ai/Refactron_lib/blob/main/README.md)
  - 🚀 [Quick Start Guide](https://github.com/Refactron-ai/Refactron_lib/blob/main/GETTING_STARTED_DEV.md)
  - 🤝 [Contributing Guidelines](https://github.com/Refactron-ai/Refactron_lib/blob/main/CONTRIBUTING.md)
  - 📋 [Code of Conduct](https://github.com/Refactron-ai/Refactron_lib/blob/main/CODE_OF_CONDUCT.md)
  
  **Ways to Contribute:**
  - 🐛 Report bugs
  - ✨ Suggest features
  - 📝 Improve documentation
  - 🔧 Fix issues
  - 🧪 Add tests
  
  **Need Help?**
  - 💬 Open a discussion
  - 🐛 Create an issue
  - 📧 Contact maintainers
  
  Thank you for being part of our community! 🙏

# Configuration for first-time contributors
firstTimeContributorWelcomeComment: |
  🌟 Congratulations on your first contribution to Refactron! 
  
  This is a special moment - you're now part of our community of developers working to eliminate technical debt and improve code quality.
  
  **What happens next:**
  - We'll review your contribution
  - Provide feedback if needed
  - Merge your changes if everything looks good
  - You'll be credited as a contributor! 🎉
  
  **Keep contributing:**
  - Look for issues labeled "good first issue"
  - Check out our [Contributing Guide](https://github.com/Refactron-ai/Refactron_lib/blob/main/CONTRIBUTING.md)
  - Join our community discussions
  
  Thank you for making Refactron better! 🚀
